version: "3.8"

services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"  # Add cluster communication port
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # Disable security features for development
      - xpack.security.enabled=false
      # Set network host to allow connections
      - network.host=0.0.0.0
      # Make sure these are set properly
      - http.port=9200
      - transport.port=9300
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    networks:
      - app-network
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_TIMEOUT=30  # Increase timeout
    networks:
      - app-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    ports:
      - "9567:9567"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend
    restart: on-failure
    
volumes:
  es_data:
    driver: local

networks:
  app-network:
    driver: bridge
