version: '3.8'

networks:
  my_network:  # Define a custom network
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports:
      - "9567:9567"  # Only frontend is exposed to the host
    networks:
      - my_network

  backend:
    build: ./backend
    expose:
      - "9567"  # Not accessible from host, only inside Docker
    networks:
      - my_network
    depends_on:
      - elasticsearch

  elasticsearch:
    build: ./elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - "9567"  # Not accessible from host
    networks:
      - my_network

volumes:
  esdata:
