version: '3'
networks:
  my_network:
    driver: bridge

services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9567"  # Accessible from host
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9567/_cat/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 1

  backend:
    build: ./backend
    ports:
      - "9567:9567"  # Accessible from hostß
    networks:
      - my_network
    depends_on:
      - elasticsearch

volumes:
  esdata:
