version: '3'
networks:
  my_network:  # Define a custom network
    driver: bridge

services:

  elasticsearch:
    build: ./elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - "9567"  # Not accessible from host
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9567/_cat/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 1

  backend:
    build: ./backend
    expose:
      - "9567"  # Not accessible from host, only inside Docker
    networks:
      - my_network
    depends_on:
      - elasticsearch

volumes:
  esdata:
