version: '2.3'
networks:
  my_network:
    driver: bridge

services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # Accessible from host
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9567/"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    ports:
      - "80:9567"  # Accessible from host
    networks:
      - my_network
    depends_on:
        elasticsearch:
          condition: service_healthy


volumes:
  esdata:
