version: "3.8"

services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    volumes:
      - es_data:/usr/share/elasticsearch/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/es-status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  frontend:
    build: ./frontend
    ports:
      - "9567:9567"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    restart: always

volumes:
  es_data:
